language: scala
jdk:
- oraclejdk7
sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package' && ci/sbt-deploy.sh
  && ci/gh-pages.sh  
after_script:
- rm -rf ci
env:
  global:
  - secure: E8yaqmeF7dkk5NwJ9beYHPd+SM6VdEsO+osE05dip+AUYdQnNotlvpBn3CbG/4dPJ5zZ6mkQ2eod3E3BcKliKrzkCQW4Kpy2sxmvZv9KQYgkqOTwHBuNw5UFh4tjaK4EACGLHHkCM1Ba/4FPZj28BFzEJDxyX7/pOB9HzajjSuo=
  - secure: OrJVzzBRNnvzNp5hALPHr/+lUz5ULXfZcrhdb9Uk9w3fQeWseDmFTKKJygLZAenIovnwHAlhayeauQMdrp5qIhMz/69KPb+dng91YI730NFyR9BpO2U9cIiOW3CDSmR3VNVspDZXJnKxL5SkcuRmsX+GK1Tdyj3WdNpADF9YMNk=
